url: https://codenestltd.github.io

# Site settings
title: Codenest - Making Software Better
email: accounts@codenest.uk
description: "Codenest is a network of experienced software consultants, specialising in agile delivery."

company:
  name: Codenest Ltd
  number: 10909723

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/Codenest_Ltd
  - title: github
    url: https://github.com/cod3nest

# Postal address (add as many lines as necessary)
address:
  - line: Clearway Accountant
  - line: Colley Way
  - line: Reigate
  - line: RH2 9JH

# Build settings
markdown: kramdown
permalink: pretty
