url: https://cod3nest.github.io

# Site settings
title: Codenest - Putting your needs first
email: accounts@codenest.uk
description: "Codenest is a network of experienced software consultants, specialising in agile delivery."

company:
  name: Codenest Ltd
  number: 10909723
  domain: codenest.uk
  fullDomain: https://www.codenest.uk
  contact:
    address: Clearway Accountant, Colley Way, Reigate, RH2 9JH
    email:
      info: accounts@codenest.uk

page:
  about:
    title: About Us
    url: /about/
  services:
    title: Our Services
    url: /services/
  careers:
    title: Careers
    url: /careers/
  contact:
    title: Contact Us
    url: /contact-us/
  terms-and-conditions:
    title: Terms and Conditions
    url: /terms-and-conditions/
  privacy-policy:
    title: Privacy Policy
    url: /privacy-policy/
  cookie-policy:
    title: Cookie Policy
    url: /cookie-policy/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/Codenest_Ltd
  - title: github
    url: https://github.com/cod3nest
  - title: linkedin
    url: https://www.linkedin.com/company/codenest-ltd

# Build settings
markdown: kramdown
permalink: pretty
